---
title: "TEMPEST20240624_H2S"
author: "Ashleigh Montgomery"
date: "2024-06-27"
output: html_document
---

#Figure out way to account for dilution by Zn acetate if volume of sample varies

#SET UP

```{r}
#Set working directory
setwd("~/R Code/TEMPEST/Porewater/Sulfide")


library(tidyverse)
library(dplyr)
library(ggplot2)
library(data.table)
library(stringr)
library(plater)
```


```{r}
#Function to calculate slope, intercept, and R-squared and return in data frame
#Fe 2 
cal_curve<-function(Conc_uM,ABS){
    model<-lm(ABS~Conc_uM)
    slope<-coef(model)[[2]]
    intercept<-coef(model)[[1]]
     R2<-summary(model)$adj.r.squared
  return(data.frame(slope=slope,intercept=intercept,R2=R2))
}
```

#IMPORT DATA

**Files required:** CSV for each plate run. Each plate should include a set of standards and QAQC checks (duplicates, spikes, interference)

```{r}
plates<-read_plates(
  files=c("TEMPEST20240624_H2S_plate1.csv","TEMPEST20240624_H2S_plate2.csv","TEMPEST20240624_H2S_plate3.csv"),
  plate_names = c("Plate 1","Plate 2","Plate 3"),
  well_ids_column = "Wells",
  sep=","
)

head(plates)
```

##PLOT STANDARDS 

```{r}
plates%>%
  filter(str_detect(plates$IDs,"STD"))%>%
  ggplot(aes(Std_Conc_uM,ABS1))+
  facet_wrap(~Plate)+
  geom_point()+
  geom_smooth(method="lm",se=FALSE)


stds<-plates%>%
  filter(str_detect(plates$IDs,"STD"))%>%
  group_by(Plate)%>%
  mutate(cal_curve(Std_Conc_uM,ABS1))%>%
  filter(row_number()==1)%>%
  select(Plate,slope,intercept,R2)

stds
  

```

#CALCULATE CONCENTRATIONS

```{r}
samples<-left_join(plates,stds,by="Plate")%>% #add slope/intercept info
  filter(!str_detect(plates$IDs,"STD|DUP|SPK|ppt"))%>% #filter out standards and checks
  mutate(conc_uM=((ABS1-intercept)/slope)*Dilutions)%>% #calculate concentrations
  mutate(conc_uM=ifelse(conc_uM<0,0,conc_uM))%>% #make negative values 0
  group_by(IDs)%>% 
  summarise(conc_uM=conc_uM)%>% #average triplicate reads
  separate_wider_delim(IDs,
                       delim = "_",
                       names=c("TimePoint","Date","Treatment","Grid")) #separate IDs into columns

head(samples)
```


#EXPORT
```{r}
write.csv(samples, file="TEMPEST2024_H2S.csv")
```

